### ISSUE TITLE
Add Applite to Homebrew

### ISSUE THREAD

**Issue by muescha** [milanvarady/Applite#1]
allow installation with homebrew

**Comment by milanvarady** [comment]
I opened a pull request: Homebrew/homebrew-cask#152475. The project needs at least 75 stars to be accepted, because it is not notable enough to be on hombebrew.

**Comment by muescha** [comment]
you need 8 more stars :)

**Comment by milanvarady** [comment]
Pull request merged. Applite is now added to Homebrew.
