### ISSUE TITLE
Please clarify: Can I use Applite with my existing homebrews?

### ISSUE THREAD

**Issue by muescha** [milanvarady/Applite#2]
Q: Can I use Applite with my existing homebrews?

I like to try out Applite, but I don't like to reinstall all my Apps just to use Applite. 
Also if I not like the Applite anymore, I would use homebrew as usual as before.
Also while installed Applite I still like to use the `brew` commands in Terminal

**Comment by milanvarady** [comment]
When first launching Applite or in the preferences, you can choose an already existing homebrew installation to use. All your currently installed casks will be recognized. Your brew installation won't be affected in any way that would prevent you from using it in the terminal.

**Comment by milanvarady** [comment]
Yes, it basically calls your selected brew executable. So for example if you want to install Firefox with Applite, it will call `path/to/your/brew install --cask firefox`.

**Comment by muescha** [comment]
this are good news, but it is not that clear. 

1) You describe it better at homepage and website.


2) why then this path is used?
> Where does the Homebrew installation go?
Applite has its own brew installation located at ~/Library/Application Support/Applite/homebrew

3) iFun

Here it is described that it creates a "shadow" homebrew and I need to reinstall the apps managed by homebrew:
https://www.ifun.de/applite-grafische-oberflaeche-fuer-die-installation-von-homebrew-apps-215639/

**Comment by milanvarady** [comment]
You are correct. The phrasing wasn't very clear, which could lead to confusion, so I updated the [website](https://aerolite.dev/applite) advanced FAQ section. Do you find it more understandable?

**Comment by muescha** [comment]
yes - it is more clear :)

thanks
