### ISSUE TITLE
Update errors "already installed" and others

### ISSUE THREAD

**Issue by KevinBatdorf** [milanvarady/Applite#20]
I just installed the app via homebrew about 10 minutes ago.

I opened it and pressed to update all apps, and got an already installed, force install message.

![Screenshot 2023-08-11 at 2 27 19 PM](https://github.com/milanvarady/Applite/assets/1478421/67f1fad9-a72e-4fa6-9b22-b7eea6c3f46f)

If you look behind the modal, there are no chevrons or anywhere to click for options. Also, why do I need to force install? It should be using my homebrew

I went to the Installed tab just to look around and noticed that Applite itself has an update available, but pressing this did nothing. No feedback at all besides the button state change (styling) when pressed/unpressed.

![Screenshot 2023-08-11 at 2 29 57 PM](https://github.com/milanvarady/Applite/assets/1478421/8f8bcac7-2694-46f2-8e93-63dc37dbb087)

Then went to the the menubar and pressed "check for updates" and got an error that it cant be updated because its running from where it was downloaded to 🤷‍♂️

![Screenshot 2023-08-11 at 2 35 31 PM](https://github.com/milanvarady/Applite/assets/1478421/9b4b9beb-f20c-4029-8cc9-9e896eeef0e8)

Quit and reopened applite, and all but one of the apps listed as having an update were gone (Unity editor remained)

Anyway, I just wanted to share some ux feedback.

**Comment by KevinBatdorf** [comment]
Just noticed the apps that errored were installed outside of my homebrew install. Happy to help debug

**Comment by milanvarady** [comment]
The "app already installed" error should only appear when downloading, so I'll look into that. 

The update button has already been patched and will be fixed in the next update.

I don't know why the update fails for you. I assume you have the application in the Applications folder, right?

**Comment by KevinBatdorf** [comment]
Yeah it's in the Applications directory. When I open a terminal session now I get errors like

> Error: Cask 'blender' is not installed.

I had to go and delete the apps I updated in my first screenshot, and reinstall them via homebrew

**Comment by milanvarady** [comment]
I'm closing this issue since most of the bugs mentioned have already been fixed.
