### ISSUE TITLE
Switching appearance display incorrect

### ISSUE THREAD

**Issue by mieai** [milanvarady/Applite#32]
Choose a color scheme for the appearance, from dark to system font color will be white, and the background color will be white.

**Comment by milanvarady** [comment]
Changing the color scheme is bugged for some reason. Switching back to the system setting sometimes only partially changes the colors. I've seen other people experience this problem in various applications, but the only solution I've found is a workaround. We first change the color scheme directly to light or dark, depending on the system setting, and then back to the "system" (`nil`) option. For example, if the system is set to light, and we are in dark mode, we first change it back to light, and then after a short delay, to the "system" (`nil`) setting.

If anyone finds a better solution, that would be great.

**Comment by mieai** [comment]
Thanks for your work and hope it gets better.😜
