### ISSUE TITLE
updating installed apps not working

### ISSUE THREAD

**Issue by vordenken** [milanvarady/Applite#4]
Hi,
first of all - really nice looking app! Love the idea, keep it up :)

I can successfully install new apps with your app but cannot update existing ones, it just says "error" after a few seconds. How can I debug this?

**Comment by milanvarady** [comment]
The error message should be logged to 'Console.app'. Open the console app, and at the top press the start button to begin collecting logs. After the error has occurred pause logging and search for applite and filter for errors and faults. Let me know if you can find the bug this way.

**Comment by soheilpro** [comment]
I have the same issue.

Here's the error message that was logged:
```
Failed to run brew command "<private>" with arguments "<private>", output: <private>
```

**Comment by milanvarady** [comment]
We can't see the output because private mode is turned on. You can follow this [stack exchange answer](https://superuser.com/questions/1532031/how-to-show-private-data-in-macos-unified-log/1532052#1532052) to reveal the actual output. It's a bit tedious to do, but it would help me debug the issue.

**Comment by vordenken** [comment]
I enabled the actual output and found out its my fault... The 2 apps listed to upgrade aren't on my Mac anymore - I removed them without brew so brew probably thinks they should be installed.

**Comment by milanvarady** [comment]
Thank you for investigating this issue. I'm closing this issue for now.
