### ISSUE TITLE
Addition of the option to entirely uninstall Apps 

### ISSUE THREAD

**Issue by DeEskalator** [milanvarady/Applite#41]
Hey,
I really love your App and it's something I have been searching for for quite a while. 

Recently, while using Applite, I noticed that there isn't an option to fully uninstall applications using the --zap argument that is available in the Homebrew CLI. The '--zap' argument allows for a more comprehensive removal of apps, getting rid of preferences, system library data that the app wrote and application settings, thus freeing up additional space and ensuring a clean uninstall. It would be really neat if Applite had something like an "Uninstall Entirely" button

**Comment by milanvarady** [comment]
Hi, I'm looking into implementing this feature. Would you rather have a toggle in the settings like "Uninstall apps completely" so that all apps are always completely uninstalled, or have a button next to the app so that you can do it on an app-by-app basis?

**Comment by DeEskalator** [comment]
Maybe like the button to uninstall + like a downward facing arrow next to it that presents the option to uninstall entirely when pressed

**Comment by milanvarady** [comment]
I added this functionality in the [v1.2.2 update](https://github.com/milanvarady/Applite/releases/tag/v1.2.2).

**Comment by DeEskalator** [comment]
That's great. Thank you. 

So trash is uninstall and trash.fill is uninstall entirely 😂? - Nice detail
