### ISSUE TITLE
Option to update all apps

### ISSUE THREAD

**Issue by canonizer** [milanvarady/Applite#42]
First of all, thanks for the great app!

Would it be possible to add an option to update all apps? This also includes casks with `auto_updates true` or `version :latest`.

The corresponding `brew` options are `-g` or `--greedy`, for instance `brew outdated --cask -g` to list all updates, and `brew upgrade --cask -g` to install them.

**Comment by milanvarady** [comment]
This functionality is now available in the [v1.2.2 update](https://github.com/milanvarady/Applite/releases/tag/v1.2.2).

**Comment by canonizer** [comment]
Thanks for implementing this! I've checked, and it works for me.

However, it would be great to have a switch (a checkbox, for instance) in Applite's settings to turn on showing all updates permanently. Would it be possible to add this?

**Comment by milanvarady** [comment]
I'll consider it in the next release.

**Comment by canonizer** [comment]
Great! Should I create a separate issue for this?

**Comment by milanvarady** [comment]
No need for that. I added this to my todo list.
