### ISSUE TITLE
Add HTTP/SOCKS proxy support

### ISSUE THREAD

**Issue by virskor** [milanvarady/Applite#46]
Add HTTP/SOCKS proxy support plz

**Comment by kyle18th** [comment]
I also need this feature.

**Comment by zy6p** [comment]
Can it use the system proxy?

**Comment by edisonX-sudo** [comment]
LGTM

**Comment by lijc210** [comment]
+1

**Comment by bro0k** [comment]
+1

**Comment by milanvarady** [comment]
Hi everyone. I have implemented proxy support and I'm looking for someone to test it out before it goes live. If anyone would be willing to test it please DM me on Discord (milanvarady) or X (@MilanVarady).

**Comment by milanvarady** [comment]
Proxy support is now live. Applite uses the system proxy settings, it supports HTTP, HTTPS, and SOCKS5. It can only use one protocol, so if you have multiple proxy protocols enabled, you may want to select which one you prefer in the settings.
