### ISSUE TITLE
Long buffering time for opening pages

### ISSUE THREAD

**Issue by ricklei2777** [milanvarady/Applite#51]
> Tun mode with ClashX enabled still doesn't work.

## WTF？！What do I have to do to get it to show the content? 

<img width="1476" alt="image" src="https://github.com/milanvarady/Applite/assets/96427310/a9bb2fb0-1491-4cbd-82d6-9fa4b5c08b1e">

**Comment by milanvarady** [comment]
@ricklei2777 Loading takes about 1-3 seconds for me. It shouldn't take more than 10 seconds. The data is fetched from the [Homebrew API](https://formulae.brew.sh/api/). To be more exact Applite loads data from these two URLs:

- `https://formulae.brew.sh/api/cask.json`
- `https://formulae.brew.sh/api/analytics/cask-install/365d.json`

All other information (i.e. installed apps) is loaded from your computer.

Please check if your computer can reach the Homebrew API.
