### ISSUE TITLE
.zshrc File corruption is lost

### ISSUE THREAD

**Issue by alucardzlh** [milanvarady/Applite#53]
1、brew install applite
2、Error message related to gettext is displayed
3、brew uninstall gettext
4、brew install applite

ZSH fails
zshrc file corruption is lost
There is no backup, and I am distressed

Apple M1 Pro
macOS sonoma 14.3.1

**Comment by milanvarady** [comment]
So if I understand you correctly, you tried to install Applite via brew, it failed to install the `gettext` dependency and then your zshrc got corrupted. 

Unfortunately this seems to be a problem with brew and not really Applite. Perhaps you could share the terminal output so I can have a closer look.

**Comment by milanvarady** [comment]
It has been a while without a response. I'm closing the issue.
