### ISSUE TITLE
This software seems to be unable to scan local software installations?

### ISSUE THREAD

**Issue by xinx1n** [milanvarady/Applite#54]
1. The installation interface was unable to detect the software I had previously installed without using homebrew cask.
2. After manually uninstalling the software I obtained from applite, the app failed to recognize this action.

**Comment by milanvarady** [comment]
Applite uses [Homebrew](https://brew.sh/) as its backend. Homebrew is used to download, uninstall, and manage the applications. Homebrew keeps track of the apps it installs and Applite uses that to get information about the installed applications, so any app installed or uninstalled manually will not be recognized.
