### ISSUE TITLE
Terminals =! IDE's

### ISSUE THREAD

**Issue by tempusthales** [milanvarady/Applite#6]
Currently terminals such as Warp, iTerm 2, Hype, etc. are listed under IDE's which I think they are not even if they are used for coding.  Can these be recategorized as what they are?

On that note can the terminal Tabby be added please? [https://tabby.sh/](https://tabby.sh/)
Formulae: [brew install --cask tabby](https://formulae.brew.sh/cask/tabby#default)

**Comment by milanvarady** [comment]
I will change this in the next update, and add tabby.

**Comment by milanvarady** [comment]
Changed in the 1.1 release.
