### ISSUE TITLE
Will brew formulae be supported?

### ISSUE THREAD

**Issue by yezhoujie** [milanvarady/Applite#63]
Any plan to support not only the brew `cask` but also the other packages and scripts?

**Comment by milanvarady** [comment]
I don't plan to support brew formulae, the app is focused on downloading and managing casks. My goal with this app is to bring the convenience of homebrew casks to non-technical people. My rationale is that if you want to download formulae, you should already be familiar with the command line, as formulae are mostly command line tools.

If you are looking for a GUI option to manage formulae you may want to use [Cork](https://github.com/buresdv/Cork) instead.

**Comment by iamsk** [comment]
formulae support +1, it's all about 'apps', please have a consideration, thanks.
