### ISSUE TITLE
Sync already deleted apps

### ISSUE THREAD

**Issue by mortum5** [milanvarady/Applite#69]
I installed several apps through Applite and then uninstalled them through CleanMyMac X. But Applite doesn't track these changes.

**Comment by milanvarady** [comment]
> Applite uses [Homebrew](https://brew.sh/) as its backend. Homebrew is used to download, uninstall, and manage the applications. Homebrew keeps track of the apps it installs and Applite uses that to get information about the installed applications, so any app installed or uninstalled manually will not be recognized.

_Originally posted by @milanvarady in https://github.com/milanvarady/Applite/issues/54#issuecomment-2028623729_

**Comment by mortum5** [comment]
Oh, I see, thank you!
