### ISSUE TITLE
[Feature Request] Add in settings an option to pick Intel or M processor

### ISSUE THREAD

**Issue by justeepin** [milanvarady/Applite#72]
I searched and found Kid3 (and a few other apps) BUT I couldn't install them because they were the Intel versions and not the AMD versions for the M processor line.  It would be nice if there was a setting where you could pick the processor and it would download the correct one.

**Comment by milanvarady** [comment]
Applite uses [Homebrew](https://brew.sh/) as its backend, which is not built by me. I can't change things related to the way things are downloaded. Brew should automatically select the correct binary to download for your chip architecture.
