### ISSUE TITLE
[Feature Request] Ability to save the dmg install images

### ISSUE THREAD

**Issue by justeepin** [milanvarady/Applite#73]
How about offering the option to save the dmg (or zip) installer files for those of us that like to keep backups of them?

**Comment by milanvarady** [comment]
As with your previous issue I'm not in charge of the actual download process, [brew](https://brew.sh) does the heavy lifting. DMG, ZIP, and PKG files are cached to `~/Library/Caches/Homebrew/Cask`, where they are available until they're cleaned by brew.
