### ISSUE TITLE
[Feature Request] Suggest new app to be added

### ISSUE THREAD

**Issue by justeepin** [milanvarady/Applite#74]
I searched for KDEConnect but it wasn't available, how about a way to request apps be added to the database?

**Comment by milanvarady** [comment]
Again, Applite gets its apps from [brew](https://brew.sh/). If you want to add an app, add it to brew or ask the developers to do so.

**Comment by vstar37** [comment]
why I cannot find [sniffnet](https://formulae.brew.sh/formula/sniffnet#default) on Applite?

**Comment by milanvarady** [comment]
Sniffnet is a formula not a cask, even though it looks like a desktop application. Applite only downloads casks.
