### ISSUE TITLE
Feature: Updating apps leads to reorganization of icons in Launchpad

### ISSUE THREAD

**Issue by PanterSoft** [milanvarady/Applite#80]
Hi,

I have experienced that when updating apps they get reorganized in the launchpad which is sometimes annoying if you have structure with folders where the applications are inside.

maybe there is a way to make sure that the icons stay where they are ?

**Comment by milanvarady** [comment]
Hi,

Applite uses [Homebrew](https:/brew.sh/) as its backend to download and update the apps. I have no way of controlling the update process. This is likely an issue with macOS or Homebrew.
